//! Fbank parity against the reference dumps.
//!
//! The reference intermediates are generated by
//! `scripts/asr/vosk/dump_reference.py` into `tmp/vosk/<model>/` (outside the
//! repo; `tmp/` is gitignored), so the parity tests are `#[ignore]` and run on
//! demand once the dumps exist.

use super::{FbankExtractor, N_MELS};

fn golden_dir() -> std::path::PathBuf {
    std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../tmp/vosk/golden/ru")
}

fn read_f32(path: &std::path::Path) -> Vec<f32> {
    let bytes = std::fs::read(path)
        .unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    bytes
        .chunks_exact(4)
        .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect()
}

fn max_abs_diff(a: &[f32], b: &[f32]) -> f32 {
    assert_eq!(a.len(), b.len(), "length mismatch");
    a.iter()
        .zip(b)
        .map(|(x, y)| (x - y).abs())
        .fold(0.0f32, f32::max)
}

#[test]
fn frame_counts() {
    let fb = FbankExtractor::new();
    // Flushed: (n + 80) / 160.
    assert_eq!(fb.n_frames(16000, true), 100);
    assert_eq!(fb.n_frames(16079, true), 100);
    assert_eq!(fb.n_frames(16080, true), 101);
    assert_eq!(fb.n_frames(0, true), 0);
    // Unflushed: only frames whose 400-sample window (starting at
    // 160·f − 120) fits: highest f with 160·f + 280 <= n.
    assert_eq!(fb.n_frames(16000, false), 99); // 160·98+280 = 15960 <= 16000
    assert_eq!(fb.n_frames(16040, false), 99);
    assert_eq!(fb.n_frames(16120, false), 100);
    // The unflushed count never exceeds the flushed one.
    assert_eq!(fb.n_frames(200, false), 0);
}

#[test]
fn range_matches_whole() {
    // Slicing a frame range out of a longer signal (with the buffer offset)
    // reproduces the whole-signal frames bit for bit away from the edges.
    let samples: Vec<f32> = (0..8000)
        .map(|i| ((i as f32) * 0.011).sin() * 0.4)
        .collect();
    let fb = FbankExtractor::new();
    let whole = fb.compute(&samples);
    // Frames 10..20 read samples [160·10−120, 160·19−120+400) = [1480, 3320).
    let window = &samples[1280..3400];
    let part = fb.compute_range(window, 1280, 10, 10);
    let a = &whole.data()[10 * N_MELS..20 * N_MELS];
    assert_eq!(a, part.data());
}

/// The fbank front end reproduces the reference `kaldi-native-fbank`
/// features (dither 0) to FFT-implementation precision.
#[test]
#[ignore = "needs tmp/vosk/ru reference dump"]
fn fbank_matches_reference() {
    let pcm = read_f32(&golden_dir().join("clip.pcm.bin"));
    let reference = read_f32(&golden_dir().join("clip.fbank.bin"));

    let fb = FbankExtractor::new();
    let feats = fb.compute(&pcm);
    assert_eq!(feats.data().len(), reference.len(), "frame count");

    let diff = max_abs_diff(feats.data(), &reference);
    println!("fbank max abs diff: {diff}");
    // The residual is FFT-implementation noise (realfft vs the reference's
    // KISS FFT), a few 1e-4 in log-mel space.
    assert!(diff < 5e-4, "fbank max abs diff {diff}");
}
