//! Feature-extraction parity against the reference dumps.
//!
//! The reference intermediates are generated by
//! `scripts/asr/gigaam/dump_reference.py` into `tmp/gigaam/<model>/` (outside
//! the repo; `tmp/` is gitignored), so the parity tests are `#[ignore]` and run
//! on demand once the dumps exist.

use super::{FeatureExtractor, MelConfig};

/// v3_ctc feature geometry.
const V3: MelConfig = MelConfig {
    n_fft: 320,
    hop_length: 160,
    n_mels: 64,
    center: false,
};

fn golden_dir() -> std::path::PathBuf {
    std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../tmp/gigaam/v3_ctc")
}

fn read_f32(path: &std::path::Path) -> Vec<f32> {
    let bytes = std::fs::read(path)
        .unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    bytes
        .chunks_exact(4)
        .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect()
}

fn max_abs_diff(a: &[f32], b: &[f32]) -> f32 {
    assert_eq!(a.len(), b.len(), "length mismatch");
    a.iter()
        .zip(b)
        .map(|(x, y)| (x - y).abs())
        .fold(0.0f32, f32::max)
}

#[test]
fn out_len_center_false() {
    // 192000 samples, n_fft 320, hop 160: (192000 - 320) / 160 + 1 = 1199.
    assert_eq!(V3.out_len(192000), 1199);
}

#[test]
fn out_len_center_true() {
    let cfg = MelConfig { center: true, ..V3 };
    // 192000 / 160 + 1 = 1201.
    assert_eq!(cfg.out_len(192000), 1201);
}

/// The computed HTK filterbank is close to the checkpoint's, but only close:
/// the checkpoint stores it in half precision. Documents the gap that forces
/// [`FeatureExtractor::new`] to take the checkpoint buffers.
#[test]
#[ignore = "needs tmp/gigaam/v3_ctc reference dump"]
fn computed_fbank_close_to_reference() {
    let reference = read_f32(&golden_dir().join("mel_fbank.bin")); // freq-major
    let n_freqs = V3.n_freqs();
    let n_mels = V3.n_mels;
    assert_eq!(reference.len(), n_freqs * n_mels);

    let ours = super::fbank::mel_filterbank(n_freqs, n_mels, 16000); // mel-major
    let mut transposed = vec![0.0f32; n_freqs * n_mels];
    for m in 0..n_mels {
        for fk in 0..n_freqs {
            transposed[fk * n_mels + m] = ours[m * n_freqs + fk];
        }
    }
    let diff = max_abs_diff(&transposed, &reference);
    println!("computed vs checkpoint filterbank max abs diff: {diff}");
    assert!(diff < 5e-3, "mel filterbank max abs diff {diff}");
}

/// Feeding the checkpoint's own filterbank and window reproduces the reference
/// log-mel to FFT-implementation precision.
#[test]
#[ignore = "needs tmp/gigaam/v3_ctc reference dump"]
fn log_mel_matches_reference() {
    let pcm = read_f32(&golden_dir().join("clip_40_12.pcm.bin"));
    let fbank = read_f32(&golden_dir().join("mel_fbank.bin")); // [n_freqs, n_mels]
    let window = read_f32(&golden_dir().join("mel_window.bin")); // [n_fft]
    let reference = read_f32(&golden_dir().join("clip_40_12.mel.bin"));

    let extractor = FeatureExtractor::new(V3, &fbank, &window);
    let mel = extractor.log_mel(&pcm);
    assert_eq!(mel.n_mels(), 64);
    assert_eq!(mel.n_frames(), 1199);
    assert_eq!(reference.len(), 64 * 1199);

    let diff = max_abs_diff(mel.data(), &reference);
    println!("log-mel max abs diff: {diff}");
    assert!(diff < 1e-3, "log-mel max abs diff {diff}");
}
