//! Rendering the trakktor skill from the live `clap::Command` (ADR-0003).
//!
//! The skill content is generated by introspecting the same `clap` definition
//! that drives the CLI, so it always matches the installed binary. Two outputs:
//! the agent-facing *guide* (`skill show`) and the on-disk *stub*
//! (`skill install`). The traversal is hand-written rather than delegated to a
//! companion crate for full control over the Markdown (design.md §4, §7).

use std::fmt::Write as _;

use clap::{Arg, ArgAction, Command};

/// `description` limit from the strict (platform/API) SKILL.md rules
/// (design.md §6): non-empty and at most this many characters.
const DESCRIPTION_MAX: usize = 1024;

/// Renders the agent-facing guide (`trakktor skill show`, design.md §2).
///
/// Without `full`, returns the narrative guide: what the tool is, when to use
/// it, and the per-command workflows, all taken from each command's
/// `about`/`long_about` (the single source of truth, ADR-0003). With `full`,
/// appends the complete reference of every command, flag, allowed value, and
/// default (§4).
#[must_use]
pub fn render_guide(command: &Command, full: bool) -> String {
    let mut out = String::new();
    render_narrative(command, &mut out);
    if full {
        out.push('\n');
        render_reference(command, &mut out);
    }
    // Drop trailing blank lines so the caller can `println!` it cleanly.
    while out.ends_with('\n') {
        out.pop();
    }
    out
}

/// Renders the on-disk discovery stub (`SKILL.md`, design.md §3, §6).
///
/// Strict-platform frontmatter (`name`, `description`, `allowed-tools`) plus a
/// minimal body that points the agent back at the binary for the live guide —
/// so the stub never goes stale between releases.
#[must_use]
pub fn render_stub(command: &Command) -> String {
    let name = command.get_name();
    debug_assert!(
        is_valid_skill_name(name),
        "skill `name` must be lowercase [a-z0-9-] and not reserved (design.md \
         §6)"
    );
    let description = stub_description(command);

    let mut out = String::new();
    out.push_str("---\n");
    let _ = writeln!(out, "name: {name}");
    let _ = writeln!(out, "description: \"{description}\"");
    let _ = writeln!(out, "allowed-tools: Bash({name}:*)");
    out.push_str("---\n\n");
    let _ = writeln!(out, "# {name}\n");
    let _ = writeln!(
        out,
        "This file is a discovery stub, not the usage guide. It stays valid \
         across `{name}` releases because it only points back at the binary.\n"
    );
    let _ = writeln!(
        out,
        "Before running any `{name}` command, load the current guide from the \
         binary itself:\n"
    );
    let _ = writeln!(
        out,
        "- `{name} skill show` — what `{name}` does, when to use it, and the \
         typical workflows."
    );
    let _ = writeln!(
        out,
        "- `{name} skill show --full` — the above plus the complete reference \
         of every command, flag, allowed value, and default, generated from \
         this exact version.\n"
    );
    let _ = writeln!(
        out,
        "The binary is the source of truth for its own interface; run those \
         first."
    );
    out
}

// ---------------------------------------------------------------------------
// narrative guide
// ---------------------------------------------------------------------------

fn render_narrative(command: &Command, out: &mut String) {
    let name = command.get_name();
    let _ = writeln!(out, "# {name}\n");
    if let Some(about) = long_or_short(command) {
        let _ = writeln!(out, "{about}\n");
    }

    let subs: Vec<&Command> = visible_subcommands(command).collect();
    if !subs.is_empty() {
        let _ = writeln!(out, "## Commands\n");
        for sub in subs {
            let _ = writeln!(out, "### {name} {}\n", sub.get_name());
            if let Some(about) = long_or_short(sub) {
                let _ = writeln!(out, "{about}\n");
            }
        }
    }
}

// ---------------------------------------------------------------------------
// full reference
// ---------------------------------------------------------------------------

fn render_reference(command: &Command, out: &mut String) {
    let _ = writeln!(out, "## Reference\n");

    // Global options are declared on the root and apply to every command
    // (cli.md); list them once here rather than under each subcommand.
    let globals: Vec<&Arg> = command
        .get_arguments()
        .filter(|a| a.is_global_set())
        .collect();
    if !globals.is_empty() {
        let _ = writeln!(
            out,
            "Global options (may appear before or after any command):\n"
        );
        for arg in globals {
            render_arg(arg, out);
        }
        out.push('\n');
    }

    let name = command.get_name();
    for sub in visible_subcommands(command) {
        render_command(sub, name, out);
    }
}

fn render_command(cmd: &Command, parent_path: &str, out: &mut String) {
    let path = format!("{parent_path} {}", cmd.get_name());
    let _ = writeln!(out, "### {path}\n");

    // The short `about` is enough here; the narrative already carried the long
    // form. Use `collapse` so a multi-line summary stays on one line.
    if let Some(about) = cmd.get_about() {
        let _ = writeln!(out, "{}\n", collapse(&about.to_string()));
    }

    let args: Vec<&Arg> = cmd
        .get_arguments()
        .filter(|a| !a.is_global_set() && !is_help_or_version(a))
        .collect();
    let (positionals, options): (Vec<&Arg>, Vec<&Arg>) =
        args.into_iter().partition(|a| a.is_positional());

    if !positionals.is_empty() {
        let _ = writeln!(out, "Arguments:\n");
        for arg in &positionals {
            render_arg(arg, out);
        }
        out.push('\n');
    }
    if !options.is_empty() {
        let _ = writeln!(out, "Options:\n");
        for arg in &options {
            render_arg(arg, out);
        }
        out.push('\n');
    }

    for sub in visible_subcommands(cmd) {
        render_command(sub, &path, out);
    }
}

/// Renders one argument as a Markdown bullet, followed by an annotation line
/// (possible values, default, env, required) when any apply (design.md §4).
fn render_arg(arg: &Arg, out: &mut String) {
    let head = if arg.is_positional() {
        format!("`<{}>`", value_name(arg))
    } else {
        let mut flags = Vec::new();
        if let Some(long) = arg.get_long() {
            flags.push(format!("--{long}"));
        }
        if let Some(short) = arg.get_short() {
            flags.push(format!("-{short}"));
        }
        let mut head = format!("`{}", flags.join(", "));
        if takes_value(arg) {
            let _ = write!(head, " <{}>", value_name(arg));
        }
        head.push('`');
        head
    };

    let mut line = format!("- {head}");
    if let Some(help) = arg.get_long_help().or_else(|| arg.get_help()) {
        let _ = write!(line, " — {}", collapse(&help.to_string()));
    }
    let _ = writeln!(out, "{line}");

    let mut notes = Vec::new();
    // Only value-taking args have meaningful allowed values; a bool flag would
    // otherwise report a noisy `true, false`.
    if takes_value(arg) {
        let possible: Vec<String> = arg
            .get_possible_values()
            .iter()
            .map(|value| value.get_name().to_string())
            .collect();
        if !possible.is_empty() {
            notes.push(format!("values: {}", possible.join(", ")));
        }
    }
    let defaults: Vec<String> = arg
        .get_default_values()
        .iter()
        .map(|value| value.to_string_lossy().into_owned())
        .collect();
    if !defaults.is_empty() {
        notes.push(format!("default: {}", defaults.join(", ")));
    }
    if let Some(env) = arg.get_env() {
        notes.push(format!("env: {}", env.to_string_lossy()));
    }
    if arg.is_required_set() {
        notes.push("required".to_string());
    }
    if !notes.is_empty() {
        let _ = writeln!(out, "  ({})", notes.join("; "));
    }
}

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

/// The full `long_about`, else the short `about`, trimmed. The long form
/// already includes the summary as its first paragraph, so the narrative needs
/// only one of them.
fn long_or_short(cmd: &Command) -> Option<String> {
    cmd.get_long_about()
        .or_else(|| cmd.get_about())
        .map(|text| text.to_string().trim().to_string())
        .filter(|text| !text.is_empty())
}

/// Subcommands to document: the user-facing ones, skipping clap's auto-injected
/// `help` subcommand and anything explicitly hidden.
fn visible_subcommands(cmd: &Command) -> impl Iterator<Item = &Command> {
    cmd.get_subcommands()
        .filter(|sub| sub.get_name() != "help" && !sub.is_hide_set())
}

/// Whether an argument carries a value (an option) versus being a pure flag.
fn takes_value(arg: &Arg) -> bool {
    !matches!(
        arg.get_action(),
        ArgAction::SetTrue |
            ArgAction::SetFalse |
            ArgAction::Count |
            ArgAction::Help |
            ArgAction::HelpShort |
            ArgAction::HelpLong |
            ArgAction::Version
    )
}

/// clap auto-adds `--help`/`--version`; they are universal, so the reference
/// omits them.
fn is_help_or_version(arg: &Arg) -> bool {
    matches!(
        arg.get_action(),
        ArgAction::Help |
            ArgAction::HelpShort |
            ArgAction::HelpLong |
            ArgAction::Version
    ) || matches!(arg.get_id().as_str(), "help" | "version")
}

/// The argument's value placeholder: its declared value name, else its id.
fn value_name(arg: &Arg) -> String {
    arg.get_value_names()
        .and_then(|names| names.first())
        .map(ToString::to_string)
        .unwrap_or_else(|| arg.get_id().as_str().to_string())
}

/// The stub `description`: the root command's summary, collapsed to one line,
/// clamped to the strict limit and YAML-escaped (design.md §6).
fn stub_description(command: &Command) -> String {
    let raw = command
        .get_about()
        .map(|about| collapse(&about.to_string()))
        .filter(|text| !text.is_empty())
        .unwrap_or_else(|| {
            format!("{} — CLI helpers for coding agents.", command.get_name())
        });
    yaml_escape(&clamp_chars(&raw, DESCRIPTION_MAX))
}

/// Validates a skill `name` against the strict frontmatter rules (design.md
/// §6): lowercase ASCII letters/digits/hyphens, and not a reserved word.
fn is_valid_skill_name(name: &str) -> bool {
    !name.is_empty() &&
        name.len() <= 64 &&
        name.chars().all(|c| {
            c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-'
        }) &&
        !matches!(name, "anthropic" | "claude")
}

/// Escapes a string for a YAML double-quoted scalar. The only characters that
/// need escaping there are `\` and `"`; bare control characters are invalid in
/// a double-quoted scalar, but [`collapse`] has already folded every control
/// character (not just whitespace) to a space before this is called.
fn yaml_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            _ => out.push(c),
        }
    }
    out
}

/// Truncates to at most `max` characters, appending an ellipsis when cut.
fn clamp_chars(s: &str, max: usize) -> String {
    if s.chars().count() <= max {
        return s.to_string();
    }
    let mut out: String = s.chars().take(max.saturating_sub(1)).collect();
    out.push('…');
    out
}

/// Collapses any run of whitespace or control characters (newlines, tabs, and
/// also NUL/ESC/DEL and the rest of C0/C1) into a single space and trims the
/// ends, so a value fits one Markdown line and stays valid inside a
/// double-quoted YAML scalar (design.md §6).
fn collapse(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut prev_space = false;
    for c in s.chars() {
        if c.is_whitespace() || c.is_control() {
            if !prev_space {
                out.push(' ');
            }
            prev_space = true;
        } else {
            out.push(c);
            prev_space = false;
        }
    }
    out.trim().to_string()
}

#[cfg(test)]
mod tests {
    use clap::{Arg, ArgAction, Command};

    use super::*;

    /// A miniature CLI standing in for the real one, exercising the traversal:
    /// nested subcommands, a positional, a flag, and an option with a default.
    fn sample() -> Command {
        Command::new("trakktor")
            .about("Helper commands for coding agents: feeds and more.")
            .long_about(
                "Helper commands for coding agents: feeds and more.\n\nUse \
                 when a task needs one of them.",
            )
            .subcommand(
                Command::new("feed")
                    .about("Work with feeds.")
                    .long_about(
                        "Work with feeds.\n\ndiscover, read, mark-read.",
                    )
                    .subcommand(
                        Command::new("read")
                            .about("Read a feed and return publications.")
                            .arg(
                                Arg::new("url")
                                    .required(true)
                                    .value_name("url"),
                            )
                            .arg(
                                Arg::new("all")
                                    .long("all")
                                    .action(ArgAction::SetTrue)
                                    .help("Include read items."),
                            )
                            .arg(
                                Arg::new("fields")
                                    .long("fields")
                                    .default_value("minimal")
                                    .value_name("list")
                                    .help("Fields to show."),
                            ),
                    ),
            )
    }

    #[test]
    fn narrative_lists_commands_without_reference() {
        let guide = render_guide(&sample(), false);
        assert!(guide.starts_with("# trakktor"));
        assert!(guide.contains("## Commands"));
        assert!(guide.contains("### trakktor feed"));
        // Long-about workflow text comes through.
        assert!(guide.contains("discover, read, mark-read."));
        // No reference section without `--full`.
        assert!(!guide.contains("## Reference"));
    }

    #[test]
    fn full_reference_exposes_flags_values_and_defaults() {
        let guide = render_guide(&sample(), true);
        assert!(guide.contains("## Reference"));
        assert!(guide.contains("### trakktor feed read"));
        assert!(guide.contains("`<url>`"));
        assert!(guide.contains("required"));
        assert!(guide.contains("`--all`"));
        assert!(guide.contains("`--fields <list>`"));
        assert!(guide.contains("default: minimal"));
    }

    #[test]
    fn stub_has_strict_frontmatter_and_points_at_the_binary() {
        let stub = render_stub(&sample());
        assert!(stub.starts_with("---\n"));
        assert!(stub.contains("name: trakktor\n"));
        assert!(stub.contains("allowed-tools: Bash(trakktor:*)\n"));
        // Description is quoted and carries the root summary.
        assert!(stub.contains(
            "description: \"Helper commands for coding agents: feeds and \
             more.\""
        ));
        // Body is a pointer, not a reference dump.
        assert!(stub.contains("trakktor skill show"));
        assert!(stub.contains("trakktor skill show --full"));
        assert!(!stub.contains("--fields"));
    }

    #[test]
    fn description_with_quotes_is_escaped_and_clamped() {
        let cmd = Command::new("trakktor").about("a \"quoted\" tool");
        assert!(
            render_stub(&cmd)
                .contains("description: \"a \\\"quoted\\\" tool\"")
        );

        let long = "x".repeat(2000);
        let cmd = Command::new("trakktor").about(long);
        let desc = stub_description(&cmd);
        assert_eq!(desc.chars().count(), DESCRIPTION_MAX);
        assert!(desc.ends_with('…'));
    }

    #[test]
    fn collapse_squeezes_whitespace_and_control_chars() {
        assert_eq!(collapse("a\n\tb   c\n"), "a b c");
        // Non-whitespace control chars (NUL, BEL, ESC, DEL) become spaces, so a
        // generated description stays valid inside a double-quoted YAML scalar.
        assert_eq!(collapse("a\u{0000}b\u{0007}\u{001b}c\u{007f}d"), "a b c d");
    }

    #[test]
    fn stub_description_has_no_control_chars() {
        let cmd =
            Command::new("trakktor").about("evil\u{0000}\u{001b}[31mabout");
        let desc = stub_description(&cmd);
        assert!(!desc.chars().any(|c| c.is_control()), "got: {desc:?}");
    }

    #[test]
    fn skill_name_rules() {
        assert!(is_valid_skill_name("trakktor"));
        assert!(!is_valid_skill_name("Trakktor"));
        assert!(!is_valid_skill_name("claude"));
        assert!(!is_valid_skill_name(""));
    }
}
