//! Encoder parity against the reference dumps.
//!
//! The reference intermediates are generated by
//! `scripts/asr/vosk/dump_reference.py` (onnxruntime over the published
//! ONNX) into `tmp/vosk/golden/<model>/`; model files live under
//! `tmp/vosk/models/<model>/`. Both live outside the repo, so the parity
//! tests are `#[ignore]` and run on demand.

use super::{EncoderSeam, Precision, VoskModel};
use crate::asr::vosk::weights;

fn model_dir(name: &str) -> std::path::PathBuf {
    std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../tmp/vosk/models")
        .join(name)
}

fn golden_dir(name: &str) -> std::path::PathBuf {
    std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../tmp/vosk/golden")
        .join(name)
}

fn read_f32(path: &std::path::Path) -> Vec<f32> {
    let bytes = std::fs::read(path)
        .unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    bytes
        .chunks_exact(4)
        .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect()
}

fn max_abs_diff(a: &[f32], b: &[f32]) -> f32 {
    assert_eq!(a.len(), b.len(), "length mismatch");
    a.iter()
        .zip(b)
        .map(|(x, y)| (x - y).abs())
        .fold(0.0f32, f32::max)
}

/// Offline encoder output vs onnxruntime, CPU f32.
#[test]
#[ignore = "needs tmp/vosk/models/ru and tmp/vosk/golden/ru"]
fn ru_encoder_matches_reference() {
    let w = weights::load_dir(&model_dir("ru")).unwrap();
    let model = VoskModel::load_cpu(&w, Precision::F32).unwrap();
    let pcm = read_f32(&golden_dir("ru").join("clip.pcm.bin"));
    let reference = read_f32(&golden_dir("ru").join("clip.encoder.bin"));

    let features = model.feature().compute(&pcm);
    let (encoded, frames) = model.encode(&features).unwrap();
    assert_eq!(encoded.len(), reference.len(), "frames: {frames}");
    let diff = max_abs_diff(&encoded, &reference);
    println!("encoder output max abs diff: {diff}");
    assert!(diff < 1e-3, "encoder output max abs diff {diff}");
}

/// Streaming encoder output vs onnxruntime driven chunk by chunk, CPU f32.
#[test]
#[ignore = "needs tmp/vosk/models/small-streaming-ru and its golden"]
fn small_streaming_encoder_matches_reference() {
    let w = weights::load_dir(&model_dir("small-streaming-ru")).unwrap();
    let model = VoskModel::load_cpu(&w, Precision::F32).unwrap();
    let golden = golden_dir("small-streaming-ru");
    let pcm = read_f32(&golden.join("clip.pcm.bin"));
    let reference = read_f32(&golden.join("clip.encoder.bin"));

    // The reference streaming dump pads the tail with 0.8 s of silence so
    // the last window clears the readiness gate; mirror it here.
    let mut padded = pcm.clone();
    padded.extend(std::iter::repeat_n(0.0f32, 16000 * 8 / 10));
    let streaming = w.config.streaming.clone().unwrap();
    let fbank = model.feature();
    let n_frames = fbank.n_frames(padded.len(), true);
    let mut session = model.start_stream().unwrap();
    let mut out: Vec<f32> = Vec::new();
    let mut start = 0usize;
    while start + streaming.window_frames < n_frames {
        let window =
            fbank.compute_range(&padded, 0, start, streaming.window_frames);
        let (encoded, _) = session.accept(&window).unwrap();
        out.extend_from_slice(&encoded);
        start += streaming.shift_frames;
    }
    assert_eq!(out.len(), reference.len());
    let diff = max_abs_diff(&out, &reference);
    println!("streaming encoder output max abs diff: {diff}");
    assert!(diff < 1e-3, "streaming encoder max abs diff {diff}");
}
